# BEGIN_KITTY_FONTS
font_family      family='IosevkaTerm Nerd Font' postscript_name=IosevkaTermNF
bold_font        auto
italic_font      auto
bold_italic_font auto
font_features    IosevkaTermNF                +ss14
font_features    IosevkaTermNF-SemiBold       +ss14
font_features    IosevkaTermNF-Italic         +ss14
font_features    IosevkaTermNF-SemiBoldItalic +ss14
# END_KITTY_FONTS

# BACKGROUND
background_opacity 0.98
background_blur    1

# AUDIO
enable_audio_bell  no

